### PR TITLE
Replace deprecated setup.py with pyproject.toml

### PR DESCRIPTION
**Pull request by Armavica**
I don't want to be too intrusive, but I thought that you might maybe want to replace the deprecated `setup.py` with `pyproject.toml`, which is a more recent standard for package building configuration, and other tools as well (such as linter, formater, etc.): https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

I added the optional plotting dependencies as `extra`, but another name could be used, for example `plotting`.

I removed `scikit-learn` because I couldn't find where it was used anywhere, did I miss something?

As far as I can say, `pip` builds and installs the exact same package (up to some trivial metadata differences) before and after this change.

### CODE REVIEW

**Comment by nchopin** [comment]
Why not, but at the same time, I am trying to fix this: 
https://github.com/readthedocs/readthedocs.org/issues/10527#issuecomment-1647408453
where I manage to compile the doc (using sphinx) locally, but it does not work on RTD (read the docs), as you can see here:
https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/
(click on "modules"). 

BTW, `scikit-learn` appears in module `binary_smc.py`, a module I have just removed to try to debug this issue, but to no avail. I am going to put it back with the next commit. 

If you have any insight about this, and / or think this replacement could help in any way, please let me know. Otherwise, I'll try other things first

**Comment by nchopin** [comment]
Also, this issue is the reason why I have included all these libraries in `requirements.txt`, in an attempt to make the RTD version compile properly, but again to no avail. 
Now, I have decided to have a second `requirements.txt', which is specific to RTD (you can find it in `docs/source/`, and the RTD config file `readthedocs.yaml` points to it), so we can remove these un-necessary requirements in the *true* `requirements.txt` file.

**Review by nchopin — APPROVED** [review]

**Comment by nchopin** [comment]
HELP! 

I think this commit actually broke my local install. To test it, I re-installed the package:
> pip install -e . 
and now most scripts do not run any more, and complain about modules / objects that cannot be imported; in particular, it cannot find:
particles.FeynmanKac

This particular class is actually defined in module particles.core, but it should (and was) accessible as particles.FeynmanKac because of this particular line in `__init__.py`: 
https://github.com/nchopin/particles/blob/ee1d19e0c1abbc0811a4e7af20348e76cc3ad856/particles/__init__.py#L3C1-L3C53

What am I missing ? Does this pyproject.toml new format ignore the `__init__.py` file for some reason ?

**Comment by nchopin** [comment]
Another issue:
I don't understand the following line:
https://github.com/nchopin/particles/blob/ee1d19e0c1abbc0811a4e7af20348e76cc3ad856/INSTALL#L59C1-L59C32

It does not work in zsh, but it does seem to work on bash. What's the magic behind it, and can we replace it by something which is not shell-dependent?

**Comment by Armavica** [comment]
## Installation issues

This is very strange, because it works for me. What was the output of `pip install -e .`? Were you in the correct directory?

The following sequence of commands works for me, when ran in the project directory:

``` bash
# Create a clean conda environment with pip in it
conda create -n particles-env pip
# Activate the environment
conda activate particles-env
# Use pip to install the package 
pip install -e .
# Print the docstring of FeynmanKac to prove that it works
python -c "from particles import FeynmanKac; help(FeynmanKac)"
```

## zsh issues

Regarding the zsh issue, indeed it looks like you need to quote the package name, because zsh interprets square brackets differently (sorry, I was not aware of that issue):
``` zsh
pip install -e '.[extra]'
```
This syntax is just a way to install optional dependencies for a package, for example you could do `pip install particles` to install the package from `PyPI` with just the basic dependencies, or `pip install particles[extra]` to also install what corresponds to the `extra` dependencies mentioned in the `pyproject.toml`.

## scikit-learn

Indeed, sorry, I missed it. In that case you might want to add it to the `pyproject.toml` file too, so it is installed automatically: https://github.com/nchopin/particles/blob/ee1d19e0c1abbc0811a4e7af20348e76cc3ad856/pyproject.toml#L14-L19

## RTD issues

I will have a look at it.

**Comment by Armavica** [comment]
So, about the RTD failure, I think that there is a syntax error, you need to transform the `-` before `path` into a space:

```
python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .
```

I think you could also remove this requirements file, and add the required dependencies as an optional group (for example `docs`) in the `pyproject.toml`, so that you would just need to `pip install .[docs]`.

**Comment by nchopin** [comment]
RTD: thank you so much, it works! I was really about to give up on that one. :-)

Installation : I think you're right, I managed to install it too properly on two separate machines. I don't know what I did on my home computer, but at least I am relieved that the package was not left in a broken / uninstallable state. 

zsh: I added a mention in INSTALL about this.

**Comment by Armavica** [comment]
Great, I am glad it worked! :) You should probably be able to remove both `requirements.txt` and `docs/source/requirements.txt` files now, now that everything uses the `pyproject.toml` I think?

**Comment by nchopin** [comment]
Good point, I need to clean up this and other things in the doc any way, will do it asap.

**Comment by nchopin** [comment]
Just one last remark about ``pyproject.toml``: 
From time to time, when I install the package, the datasets (which are in ``particles/datasets``, and obviously are not python files) are not installed, so I can no longer access them. (This does not happen with `pip install -e .`, but might with ``pip install --user .`` for instance.)

I looked up possible fixed while using  ``pyproject.toml``,  found this: 
https://setuptools.pypa.io/en/latest/userguide/datafiles.html#beta
and followed the instructions. However, I get an error msg when I try to re-install the package: ``Cannot declare ('tool', 'setuptools', 'packages', 'find') twice``.

If you know by chance how to deal with this, I'd be interested, but, if not, no big deal, I guess I should recommend to always install in editable mode.

**Comment by Armavica** [comment]
I just created a PR on `experimental` which I believe fixes the issue.

**Pull request merged**
