### PR TITLE
Fix setup.py for pip install

### PR DESCRIPTION
**Pull request by maxjcohen**
Replace the if/else statement in the setup.py for choosing the installation process (with or without Fortran). This allows pip to install the package, even when no Fortran compiler can be found.

### CODE REVIEW

**Comment by nchopin** [comment]
By pip, you mean installing from local files, or from PyPI? 
Anyway, I merged the commit, then had to fix various problems with ReadTheDocs (which still complained of the lack of a fortran compiler for some reason). I managed to install particles (from PyPI) in a freshly created env. Seems everything is ok now. Thx!

**Comment by maxjcohen** [comment]
Hi, yes I mean installing by pip from local files (or from `pip install git+https://github.com/nchopin/particles`). I haven't tried PyPI yet, but if you found that it works, I guess we can leave it to that.
Actually, the ModuleNotFound exception only triggers if numpy is not installed, I could'nt figure a way to check for the fortran compiler itself. This way, installing via pip works if we starting from a fresh environment. Unfortunatly, installing the module on a fresh environment *with* numpy still causes an error I can't catch.

**Comment by nchopin** [comment]
yeah, this fortran dependency is quite a pain... Did you try with the latest version? I removed the ModuleNotFound condition from the try/except block, so as to catch any error that could occur.

**Comment by maxjcohen** [comment]
I tried again with the latest version, on a clean Dockerfile just to stay on the safe side. This script runs smoothly:

```Dockerfile
FROM python:latest

WORKDIR /home/user/
ENV VENV=/home/user/.env/

# Install venv
RUN python3 -m pip install --upgrade --user pip virtualenv
RUN python3 -m virtualenv $VENV
RUN $VENV/bin/pip install git+https://github.com/nchopin/particles

# Import particles
RUN $VENV/bin/python -c "import particles"
```

If we add a numpy installation in the middle, the usual uncaught error in raised (even with the except all exception).

```Dockerfile
RUN python3 -m virtualenv $VENV
RUN $VENV/bin/pip install numpy 
RUN $VENV/bin/pip install git+https://github.com/nchopin/particles
```

By the way, in the documentation, you wrote as the recommended method:
```bash
cd some_folder_of_your_choosing
git clone https://github.com/nchopin/particles.git
pip install --user . 
```
These lines can be replaced by `pip install git+https://github.com/nchopin/particles`

**Pull request merged**
