### PR TITLE
Resample directly in logspace

### PR DESCRIPTION
**Pull request by AdrienCorenflos**
This should be complemented with make the "W" attribute of the Weight class be a property.

### CODE REVIEW

**Comment by AdrienCorenflos** [comment]
I think the residual resampling can be adapted with very little effort by normalizing in the logspace when passing the residual weights to the multinomial resampler but I'm not really sure about the ssp one. Maybe it can be rephrased in terms of logit functions

**Comment by AdrienCorenflos** [comment]
You can merge a subpart of the commit if you wish to.

I don't understand your point about the under/overflow. I am not addressing normalisation here.

Also note that something like this would work as a normalizer preventing underflow/overflow:
```python
from scipy.special import logsumexp

def normalise(lw):
    return lw - logsumexp(lw)
```

**Comment by AdrienCorenflos** [comment]
See this:

https://colab.research.google.com/drive/1riyVPiuNqCxGPpNPuc36IVSzGUEvHol8?usp=sharing

**Comment by nchopin** [comment]
I fixed manually the following issues in the master branch: 
* the unreferenced name in resampling.resampling
* the issue with the int dtype, which turns out to be more complicated that I thought, see below.

Regarding the "resampling on log-scale", I will think about it, but right now (as the book is about to get published) I'd rather not introduce extra features in the core packages. Thus, I'm going to close this issue. Again, thanks a lot for your feedback. 

Issue with dtype
============

Boring point for most ppl, but I'm going to document this here in case this issue bites me again in the future. In numpy this instruction is legit:

x = np.zeros(3, dtype='int')  # use a string to choose dtype; default int type is int64

However, recent versions of numba refuse to compile this instruction. I thought it was because of the string, but apparently this is due to the fact that you need to specify precisely which type of ints you want; e.g. 

x = np.zeros(3, dtype=np.int64)  # works in numba 

At some point, I fixed this issue by putting np.int32 in the two-three functions that were using numba; but the other parts of the module were still using "int", which agains defaults to int64 in numpy. From now on, the package use explicitly int64 everywhere (in module resampling).

**Pull request closed without merging**
