### PR TITLE
LinearGauss Model added in StateSpaceModel 

### PR DESCRIPTION
**Pull request by sakira**

### CODE REVIEW

**Comment by sakira** [comment]
Chapter 10, page 163: LinearGauss model seems to be assumed that the model can be imported from state_space_models, but it actually was not defined. The model is defined in Page 162.

**Comment by nchopin** [comment]
Hi,
I moved linear Gaussian state-space models to the kalman module. The rationale is that, once you have defined such a model, you can pass it to class Kalman to perform Kalman filtering; see here for more information:
https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/kalman.html

However, you're right, I forgot to update the book when I made that change... Sorry. 
It's not good practice to have the same class defined in two different places, so I will discard this PR.  However, if you think it's a problem, you can open an issue, and I will try to think of a way to make the same LinearGaussian class available in both modules. (Should be possible, but I need to check, especially regarding circular dependencies).

**Comment by sakira** [comment]
Hi,
 Sorry, I did not notice that and I agree with you its not a good practice
to have same class in different places.
I will try to be more careful next time before I request any modification.
Thanks for your time.
Best regards,
Sakira

**Comment by nchopin** [comment]
no probs!

**Pull request closed without merging**
